### ISSUE TITLE
Hey, experiencing this when calling GET call for lastTrade

### ISSUE THREAD

**Issue by BJKhunt** [alpacahq/alpaca-trade-api-js#114]
RequestError: Error: getaddrinfo ENOTFOUND data.alpaca.markets
    at new RequestError (C:\Users\Brijesh\Desktop\TrashBin\againgiveit\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\Brijesh\Desktop\TrashBin\againgiveit\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\Brijesh\Desktop\TrashBin\againgiveit\node_modules\request-promise-core\lib\plumbing.js:46:31)    at self.callback (C:\Users\Brijesh\Desktop\TrashBin\againgiveit\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (C:\Users\Brijesh\Desktop\TrashBin\againgiveit\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  cause: Error: getaddrinfo ENOTFOUND data.alpaca.markets
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'data.alpaca.markets'
  },
  error: Error: getaddrinfo ENOTFOUND data.alpaca.markets
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'data.alpaca.markets'
  },
  options: {
    method: 'GET',
    uri: 'https://data.alpaca.markets/v1/last/stocks/AAPL',
    qs: {},
    headers: {
      'content-type': 'application/json',
      'APCA-API-KEY-ID': 'blah',
      'APCA-API-SECRET-KEY': 'blah'
    },
    json: true,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
RequestError: Error: getaddrinfo ENOTFOUND data.alpaca.markets
    at new RequestError (C:\Users\Brijesh\Desktop\TrashBin\againgiveit\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\Brijesh\Desktop\TrashBin\againgiveit\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\Brijesh\Desktop\TrashBin\againgiveit\node_modules\request-promise-core\lib\plumbing.js:46:31)    at self.callback (C:\Users\Brijesh\Desktop\TrashBin\againgiveit\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (C:\Users\Brijesh\Desktop\TrashBin\againgiveit\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  cause: Error: getaddrinfo ENOTFOUND data.alpaca.markets
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'data.alpaca.markets'
  },
  error: Error: getaddrinfo ENOTFOUND data.alpaca.markets
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'data.alpaca.markets'
  },
  options: {
    method: 'GET',
    uri: 'https://data.alpaca.markets/v1/last/stocks/MSFT',
    qs: {},
    headers: {
      'content-type': 'application/json',
      'APCA-API-KEY-ID': 'blah',
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

**Comment by BJKhunt** [comment]
i got the solution
