### ISSUE TITLE
News Images field is undefined

### ISSUE THREAD

**Issue by ogtega** [alpacahq/alpaca-trade-api-js#211]
While listening for news objects, undefined image fields trigger a crash.
### Error output:
```js
/home/node/app/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/entityv2.js:234
    mappedNews.Images.forEach((element) => {
                      ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at AlpacaNews (/home/node/app/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/entityv2.js:234:23)
    at /home/node/app/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/news_websocket.js:59:85
    at Array.forEach (<anonymous>)
    at AlpacaNewsCLient.dataHandler (/home/node/app/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/news_websocket.js:55:14)
    at AlpacaNewsCLient.handleMessage (/home/node/app/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:215:22)
    at WebSocket.<anonymous> (/home/node/app/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:109:18)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/node/app/node_modules/ws/lib/websocket.js:1047:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/home/node/app/node_modules/ws/lib/receiver.js:502:14)
```

**Comment by drew887** [comment]
Sorry @ogtega I meant to check in sooner but does the latest version of the SDK 2.15.0 solve this issue for you? :thinking:

**Comment by drew887** [comment]
Ah okay sorry for the ping then :sweat_smile:.

It looks like I can confirm that it does work now so I will close out this ticket.
```js
  let news = await api.getNews({});

  console.log(news[0].Images.length);
  console.log(news[1].Images.length);
```
results in
```js
3
0
```
Instead of the error now in both the case that there are images and no images for a news article :+1:
