### ISSUE TITLE
ReferenceError: STATE is not defined

### ISSUE THREAD

**Issue by trobbins1981** [alpacahq/alpaca-trade-api-js#24]
I just updated to version 1.2.1, and I get this error when streaming via the websocket:

C:\MySource\BinanceBot\node_modules\@alpacahq\alpaca-trade-api\lib\resources\polygonWebsocket.js:122
        this.emit(STATE.WAITING_TO_RECONNECT, this.session.reconnectTimeout)
                  ^

ReferenceError: STATE is not defined
    at PolygonWebsocket.reconnect (C:\MySource\BinanceBot\node_modules\@alpacahq\alpaca-trade-api\lib\resources\polygonWebsocket.js:122:19)
    at WebSocket.conn.once (C:\MySource\BinanceBot\node_modules\@alpacahq\alpaca-trade-api\lib\resources\polygonWebsocket.js:32:22)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (C:\MySource\BinanceBot\node_modules\@alpacahq\alpaca-trade-api\node_modules\ws\lib\websocket.js:191:10)
    at Receiver.receiverOnFinish (C:\MySource\BinanceBot\node_modules\@alpacahq\alpaca-trade-api\node_modules\ws\lib\websocket.js:779:20)
    at emitNone (events.js:106:13)
    at Receiver.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:604:14)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:445:7)
    at Receiver.startLoop (C:\MySource\BinanceBot\node_modules\@alpacahq\alpaca-trade-api\node_modules\ws\lib\receiver.js:147:5)
    at perMessageDeflate.decompress (C:\MySource\BinanceBot\node_modules\@alpacahq\alpaca-trade-api\node_modules\ws\lib\receiver.js:382:12)
    at _decompress (C:\MySource\BinanceBot\node_modules\@alpacahq\alpaca-trade-api\node_modules\ws\lib\permessage-deflate.js:298:9)
    at _inflate.flush (C:\MySource\BinanceBot\node_modules\@alpacahq\alpaca-trade-api\node_modules\ws\lib\permessage-deflate.js:376:7)
    at afterWrite (_stream_writable.js:454:3)
    at onwrite (_stream_writable.js:445:7)
    at InflateRaw.afterTransform (_stream_transform.js:90:3)
    at Zlib.callback (zlib.js:515:5)

**Comment by nodesocket** [comment]
👍 also seeing this error upgrading.

```
/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:122
        this.emit(STATE.WAITING_TO_RECONNECT, this.session.reconnectTimeout)
                  ^

ReferenceError: STATE is not defined
    at PolygonWebsocket.reconnect (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:122:19)
    at WebSocket.conn.once (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:32:22)
    at Object.onceWrapper (events.js:286:20)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.emitClose (/home/node/macd/node_modules/ws/lib/websocket.js:191:10)
    at Receiver.receiverOnFinish (/home/node/macd/node_modules/ws/lib/websocket.js:779:20)
    at Receiver.emit (events.js:198:13)
    at finishMaybe (_stream_writable.js:646:14)
    at afterWrite (_stream_writable.js:486:3)
    at onwrite (_stream_writable.js:476:7)
    at Receiver.startLoop (/home/node/macd/node_modules/ws/lib/receiver.js:147:5)
    at perMessageDeflate.decompress (/home/node/macd/node_modules/ws/lib/receiver.js:382:12)
    at _decompress (/home/node/macd/node_modules/ws/lib/permessage-deflate.js:298:9)
    at _inflate.flush (/home/node/macd/node_modules/ws/lib/permessage-deflate.js:376:7)
    at afterWrite (_stream_writable.js:485:3)
    at onwrite (_stream_writable.js:476:7)
    at InflateRaw.afterTransform (_stream_transform.js:94:3)
    at Zlib.processCallback (zlib.js:548:8)
```

My code is:

```javascript
client.onStockTrades((subject, data) => {
    _.forEach(JSON.parse(data), (doc) => {
        console.log(doc);
    });
});
```

**Comment by nodesocket** [comment]
@andrewkim316 any idea on this bug? Breaking change in `onStockTrades`

**Comment by andrewkim316** [comment]
I'll call in the expert @ttt733

**Comment by ttt733** [comment]
Whoops - missed putting in `websockets.`. Fixing in our next release. Thanks!
