### ISSUE TITLE
[Bug]: "alpaca.data_stream_v2" crashes in `datav2/stock_websocket_v2.js` while streaming

### ISSUE THREAD

**Issue by ManfredLange** [alpacahq/alpaca-trade-api-js#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When code subscribes to `alpaca.data_stream_v2`, it crashes about twice a week with the following error (fourth time this month):

```bash
/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/stock_websocket_v2.js:70
        if (trades.length > 0 ||
                   ^
TypeError: Cannot read properties of undefined (reading 'length')
    at AlpacaStocksClient.subscribeAll (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/stock_websocket_v2.js:70:20)
    at AlpacaStocksClient.<anonymous> (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:136:22)
    at AlpacaStocksClient.emit (node:events:530:35)
    at AlpacaStocksClient.emit (node:domain:489:12)
    at AlpacaStocksClient.handleMessage (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:206:26)
    at WebSocket.<anonymous> (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:111:18)
    at WebSocket.emit (node:events:518:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/work/service/node_modules/.pnpm/ws@7.5.10/node_modules/ws/lib/websocket.js:1070:20)
    at Receiver.emit (node:events:518:28)
[nodemon] app crashed
```

### Expected Behavior

The expected behavior is for the code in line 70 of file `datav2/stock_websocket_v2.js` to handle correctly the scenario when the value of `trades` is undefined.

### SDK Version I encountered this issue in

`@alpacahq/alpaca-trade-api` version 3.1.2

### Steps To Reproduce

```markdown
Step 1: Use code like this to subscribe to a stream, to handle errors and to handle "onStockBar()":


   const dataStream = alpaca.data_stream_v2;
   dataStream.onConnect(() => {
      console.log('Connected to Alpaca data stream');
      dataStream.subscribeForBars([
         'SPXL',
         'SOXL',
         'TECL',
         'TQQQ',
         'UPRO',
         'USD',
      ]);
   });

   dataStream.onError((err) => {
      console.error('Alpaca data stream error:', err);
   });

   dataStream.onStockBar((bar: AlpacaBar) => {
      console.log('Received stock bar:', bar);
      recordBar(bar);
      trade(bar);
   });


Step 2: Start this code when the markets open

Step 3: Do this for several days and wait. The problem will show eventually
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

I don't think this is a matter of the internet bandwidth. I have about 800 MBit/sec down and about 400 MBit/sec up. Latency is less than 20, most of the time less than 10.

Since this code that causes the error runs in a separate thread, it takes down the entire process when it crashes. It's not possible to add a try-catch block.

This makes this client library highly unreliable, and therefore this error renders the library unusable for trading algorithms that depend on the stream being processed reliably without crashing.

Since the exact same call stack has now been produced for the fourth time this month, it doesn't appear to be an extreme edge case that causes this.

**Comment by markSbrandt** [comment]
unfortunately this will just get closed and not addressed ... 
https://github.com/alpacahq/alpaca-trade-api-js/issues/273

**Comment by ManfredLange** [comment]
@markSbrandt  Sadly. Thank you for the link to the issue that you filed.

And reproducing is not that hard:

I observed this issue 5 or 6 times in December 2025. It's just a matter of letting it run every day. And no, referring to the documentation won't help. The code in the client library needs to check for whether the variable "trades" is defined or not. It should be a simple fix.

Now, there is two people who are observing this. Let's see if that will make a difference.  :grin: 

cc @noramehesz

**Comment by ManfredLange** [comment]
And another instance of this error today;

```bash
/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/stock_websocket_v2.js:70
        if (trades.length > 0 ||
                   ^
TypeError: Cannot read properties of undefined (reading 'length')
    at AlpacaStocksClient.subscribeAll (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/stock_websocket_v2.js:70:20)
    at AlpacaStocksClient.<anonymous> (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:136:22)
    at AlpacaStocksClient.emit (node:events:536:35)
    at AlpacaStocksClient.emit (node:domain:489:12)
    at AlpacaStocksClient.handleMessage (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:206:26)
    at WebSocket.<anonymous> (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:111:18)
    at WebSocket.emit (node:events:524:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/work/service/node_modules/.pnpm/ws@7.5.10/node_modules/ws/lib/websocket.js:1070:20)
    at Receiver.emit (node:events:524:28)
[nodemon] app crashed
 ELIFECYCLE  Command failed with exit code 1.
```

Shouldn't take a vast amount development time to add a change whether the value of variable `trades` is `undefined` or not.

**Comment by ManfredLange** [comment]
And another instance of this bug just a couple of hours ago:

```bash
/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/stock_websocket_v2.js:70
        if (trades.length > 0 ||
                   ^
TypeError: Cannot read properties of undefined (reading 'length')
    at AlpacaStocksClient.subscribeAll (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/stock_websocket_v2.js:70:20)
    at AlpacaStocksClient.<anonymous> (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:136:22)
    at AlpacaStocksClient.emit (node:events:536:35)
    at AlpacaStocksClient.emit (node:domain:489:12)
    at AlpacaStocksClient.handleMessage (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:206:26)
    at WebSocket.<anonymous> (/work/service/node_modules/.pnpm/@alpacahq+alpaca-trade-api@3.1.2/node_modules/@alpacahq/alpaca-trade-api/dist/resources/datav2/websocket.js:111:18)
    at WebSocket.emit (node:events:524:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (/work/service/node_modules/.pnpm/ws@7.5.10/node_modules/ws/lib/websocket.js:1070:20)
    at Receiver.emit (node:events:524:28)
[nodemon] app crashed
 ELIFECYCLE  Command failed with exit code 1
```
cc @noramehesz

**Comment by noramehesz** [comment]
Hello @ManfredLange, @markSbrandt ,

Apologise for the delay. After testing the SDK I could finally reproduce the issue and fixed it in the [latest release](https://github.com/alpacahq/alpaca-trade-api-js/releases/tag/v3.1.3). 
The problem happened during a reconnection what was most probably the case for you as well, I would recommend to set the `verbose` option to `true` when creating an Alpaca instance because it can give more insight on the problem and helps troubleshooting it. 
Please updated to the latest version and let me know in any case of an issue. 
I am closing this ticket for now, but please feel free to reopen this or a new one if needed.
Have a nice day!
