### ISSUE TITLE
oauth updates breaking dataHttpRequest method

### ISSUE THREAD

**Issue by elleeott** [alpacahq/alpaca-trade-api-js#29]
version 1.2.2, getting the following:

`ReferenceError: oauth is not defined
    at Alpaca.dataHttpRequest (/Users/elleeott/projects/algo-opt/node_modules/@alpacahq/alpaca-trade-api/lib/api.js:31:14)
    at Alpaca.getBars (/Users/elleeott/projects/algo-opt/node_modules/@alpacahq/alpaca-trade-api/lib/resources/data/bars.js:10:15)
`

**Comment by mustermania** [comment]
I am getting the same issue in v1.2.2 and confirmed in api.js that `oauth` is not defined in `this.configuration` for dataHttpRequest

**Comment by ttt733** [comment]
Sorry about the delay on this - this is fixed by #31, which has been merged, and I'll be pushing a release shortly.
