### ISSUE TITLE
[bug] TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by nodesocket** [alpacahq/alpaca-trade-api-js#33]
@ttt733  new bug report. Running Node `v10.16.0` and Alpaca `1.2.3`.

```
/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:93
            params: topics.join(',')
                           ^

TypeError: Cannot read property 'join' of undefined
    at PolygonWebsocket.subscribe (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:93:28)
    at PolygonWebsocket.on (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:21:58)
    at PolygonWebsocket.emit (events.js:203:15)
    at messageArray.forEach.message (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:50:34)
    at Array.forEach (<anonymous>)
    at PolygonWebsocket.handleMessage (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:44:22)
    at WebSocket.conn.on (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:25:48)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/node/macd/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/node/macd/node_modules/ws/lib/receiver.js:422:14)
    at perMessageDeflate.decompress (/home/node/macd/node_modules/ws/lib/receiver.js:379:23)
    at _decompress (/home/node/macd/node_modules/ws/lib/permessage-deflate.js:298:9)
    at _inflate.flush (/home/node/macd/node_modules/ws/lib/permessage-deflate.js:376:7)
    at afterWrite (_stream_writable.js:485:3)
    at onwrite (_stream_writable.js:476:7)
    at InflateRaw.afterTransform (_stream_transform.js:94:3)
    at Zlib.processCallback (zlib.js:548:8)
```

**Comment by ttt733** [comment]
Hello, I'll need to see the code you're running in order to look into this. It looks like you're calling subscribe without a list of topics - if that's not the case, please show the list you're passing or the code that creates the list.

**Comment by trobbins1981** [comment]
I also get this, with version 1.2.3

**Comment by trobbins1981** [comment]
in the previous version 1.2.1, I also had this issue, and I had to manually fix your code

**Comment by trobbins1981** [comment]
as for how I'm calling it, I'm calling it the way it is supposed to be called, like `this.client.subscribe(['AM.*'])`

**Comment by trobbins1981** [comment]
just looking at the code in `polygonWebsocket`, the issue is easy to spot.  you're calling connect() in there with no argument when reconnecting

**Comment by nodesocket** [comment]
@trobbins1981 would be awesome if you could submit a PR with the fix for this.

**Comment by nodesocket** [comment]
@ttt733 

Bad news. Still seeing this error even though running latest `1.2.4`.

```
TypeError: Cannot read property 'join' of undefined
    at PolygonWebsocket.subscribe (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:93:28)
    at PolygonWebsocket.on (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:21:58)
    at PolygonWebsocket.emit (events.js:203:15)
    at messageArray.forEach.message (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:50:34)
    at Array.forEach (<anonymous>)
    at PolygonWebsocket.handleMessage (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:44:22)
    at WebSocket.conn.on (/home/node/macd/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:25:48)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/node/macd/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/node/macd/node_modules/ws/lib/receiver.js:422:14)
    at perMessageDeflate.decompress (/home/node/macd/node_modules/ws/lib/receiver.js:379:23)
    at _decompress (/home/node/macd/node_modules/ws/lib/permessage-deflate.js:298:9)
    at _inflate.flush (/home/node/macd/node_modules/ws/lib/permessage-deflate.js:376:7)
    at afterWrite (_stream_writable.js:485:3)
    at onwrite (_stream_writable.js:476:7)
    at InflateRaw.afterTransform (_stream_transform.js:94:3)
    at Zlib.processCallback (zlib.js:548:8)
^[[90m2019-09-13T20:00:06.809Z^[[39m ^[[31m[error]^[[39m worker exited with code 1 and signal 'null'
```
