### ISSUE TITLE
Out of Memory- Polygon Data Stream

### ISSUE THREAD

**Issue by metarama** [alpacahq/alpaca-trade-api-js#63]
My program uses the polygon data stream websocket interface for stock price updates. I left it running for last couple days. This morning it reported an 'Out of Memory' error.  Below is the error output.

0: ExitFrame [pc: 0x1376259]
Security context: 0x223b15524791 <JSObject>
    1: join [0x223b15534be1](this=0x24d707b9a611 <JSArray[126209024]>,0x299d99886eb9 <String[#1]: ,>)
    2: subscribe [0x34583e6b5139] [/work/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:97] [bytecode=0x3ecaa5042bc1 offset=17](this=0x3a1e9e24aab9 <EventEmitter map = 0x2761fc3232a1>,0x24d707b9a611 <JSArray[126209024]>)
    3: connectL...

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200630.171239.44565.0.001.json
Node.js report completed
 1: 0x9dab70 node::Abort() [/usr/local/bin/node]
 2: 0x9dbd26 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0xb3b18e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0xb3b509 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0xce68a5  [/usr/local/bin/node]
 6: 0xff4d06 v8::internal::Runtime_FatalProcessOutOfMemoryInvalidArrayLength(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x1376259  [/usr/local/bin/node]
Aborted
error Command failed with exit code 134.

**Comment by shlomikushchi** [comment]
Hi,
can you point out what you are doing in your code that resulted in this error?

**Comment by metarama** [comment]
My code is identical to the stream examples shown in this repo. With handlers for various socket events and finally calling connect(). The connect handler calls subscribe() with the list of channels. All this is standard as shown in the examples.

Today again I got a crash. I did some debugging. I think I found the problem in the file:
 alpaca-trade-api-js/lib/resources/polygonWebsocket.js

At line# 100 the 'this.channels' array doubles in length after every 'reconnect'. Thus it can grow indefinitely.  Today I had 'AM' subscribed to 107 symbols. I saw three reconnections with the console msg 'Attempting Polygon websocket reconnection...'. On the third reconnection my program crashed at line# 100 with error msg "Invalid array length'.

Here's a fix I have in mind.  Replace line #127 of polygonWebsocket.js that is, 'this.connect(this.channels)' as follows:

const currChannels = this.channels
this.channels = []
this.connect(currChannels)

**Comment by metarama** [comment]
Repeated Reconnection causes 'Allocation failed - JavaScript heap out of memory' error. I created multiple instances of Alpaca object with identical connection parameters. So I can subscribe to just twenty symbols per data stream. I saw several 'Attempting Polygon websocket reconnection...' console messages and then the process exited with 'heap out of memory' error.

BTW, assuming the mem error is fixed, can I create multiple instances of Alpaca object as described above?

**Comment by shlomikushchi** [comment]
Hi,
I will test this soon.
it's a bit weird that after 3 re-connections we get this memory leak, but let's see
what do you mean by "multiple instances of Alpaca object"?

**Comment by shlomikushchi** [comment]
Hi, I've been executing the `websocket_listener.js` sample code all day yesterday and I did not experience any errors or memory leaks.
in fact, it still runs and memory consumption isn't over 20k
are we talking about the same code you executed?

**Comment by metarama** [comment]
The websocket_listener.js is setup to NOT use Polygon. I am using Polgyon to subscribe (channels A.* or AM.*) for over 50 symbols. The sample could be modified for this scenario and left running to reproduce the memory error.

The reconnect handling source code in the file "alpaca-trade-api-js/lib/resources/polygonWebsocket.js" needs to be exercised to reproduce the error.

Thank you so much for looking into this error.

**Comment by metarama** [comment]
Any updates or thoughts on this issue? How to resolve it? After running without stopping for couple of days below is the error from yesterday.

 /work/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:100
        this.channels = this.channels.concat(topics)
                                      ^

RangeError: Invalid array length
    at Array.concat (<anonymous>)
    at PolygonWebsocket.subscribe (/work/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:100:39)
    at PolygonWebsocket.connectListener (/work/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:23:46)
    at PolygonWebsocket.emit (events.js:223:5)
    at /work/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:54:34
    at Array.forEach (<anonymous>)
    at PolygonWebsocket.handleMessage (/work/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:48:22)
    at WebSocket.<anonymous> (/work/node_modules/@alpacahq/alpaca-trade-api/lib/resources/polygonWebsocket.js:28:48)
    at WebSocket.emit (events.js:223:5)
    at Receiver.receiverOnMessage (/work/node_modules/@alpacahq/alpaca-trade-api/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:223:5)
    at Receiver.dataMessage (/work/node_modules/@alpacahq/alpaca-trade-api/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/work/node_modules/@alpacahq/alpaca-trade-api/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/work/node_modules/@alpacahq/alpaca-trade-api/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/work/node_modules/@alpacahq/alpaca-trade-api/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Receiver.Writable.write (_stream_writable.js:309:11)
    at TLSSocket.socketOnData (/work/node_modules/@alpacahq/alpaca-trade-api/node_modules/ws/lib/websocket.js:872:35)
    at TLSSocket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
error Command failed with exit code 1.

**Comment by shlomikushchi** [comment]
Hi,
I am now executing the websocket_listener.js with polygon data with these subscriptions: `['trade_updates', 'AM.*', 'A.*', 'Q.*', 'T.*']`
let's see what happens

**Comment by shlomikushchi** [comment]
update: almost 24 hours, process memory below 100MB.
running on a windows machine

**Comment by shlomikushchi** [comment]
so, I executed the code example for 48 hours, with polygon data, subscribing to * updates (a lot of updates)
Haven't seen any issue with memory.

you could try basing your code on that example, or if you could provide me with code that I could execute locally and get this issue

**Comment by Prefontim** [comment]
I also have this issue.  I applied the fix from @metarama but I still get the issue.  @shlomikushchi , you have to have Polygon disconnects to get this issue.  After a couple of reconnects, you will run out of memory
