### ISSUE TITLE
alpaca.getCompany() returning unhandled 404 error (try-catch doesn't work)

### ISSUE THREAD

**Issue by immanuelx2** [alpacahq/alpaca-trade-api-js#86]
When I run the following:
```
alpaca.getCompany('AMD').then(data => console.log(data));
```
It works on most assets, but on some (for example '**KRTX**') I get the following error:

```
Unhandled rejection StatusCodeError: 404 - {"error":"Not Found"}
    at new StatusCodeError (C:\Users\imman\OneDrive\Websites\Stocks2\node_modules\request-promise-core\lib\errors.js:32:15)     
    at Request.plumbing.callback (C:\Users\imman\OneDrive\Websites\Stocks2\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\imman\OneDrive\Websites\Stocks2\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\imman\OneDrive\Websites\Stocks2\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\imman\OneDrive\Websites\Stocks2\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\imman\OneDrive\Websites\Stocks2\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Wrapping the .getCompany() code in a try-catch **does not to catch the exception**:
```
try {
    alpaca.getCompany('AMD').then(data => console.log(data));
} catch (err) {
    console.log(err);
}
```

How can I catch the exception?

**Comment by wwwebbify** [comment]
I am getting the same error from the Polygon server.

@immanuelx2, the reason you are not catching anything in your try-catch statement is because there is no error being thrown. What you are seeing is an uncaught failed or rejected promise from the alpaca.getCompany method (that's what 'Unhandled rejection' means).
To catch this error, use[ standard promise syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
`alpaca.getCompany(...).then(...).catch((error)=>{console.log(error)})`
or you may be able to use the async-await syntax if you want to keep the try-catch convention.

However, I don't believe catching the error will tell you anything new. 
` 'StatusCodeError: 404 - {"error":"Not Found"}' `
indicates a successful request, but the server returned a 404 error (I can't tell if you have polygon enabled or not, so it could be from either Alpaca or Polygon). This would usually indicate an incorrect endpoint in your request. 

I have tried running variations of the following:
`alpaca.polygonHttpRequest(`/meta/symbols/${this.symbol}/company`)`
even tried using v2 instead of v1 and several other endpoints. With the same 404 error being received on several of the endpoints listed in the reference section [here](https://polygon.io/docs/#get_v1_meta_symbols__symbol__company_anchor) (others were fine). 

My guess is that the SDK is fine, but that there is an issue with that portion of the polygon API, causing it to not be able to find the endpoint. I didn't notice any issues in the constructed request URI  `https://api.polygon.io/v1/meta/symbols/APPL/company` , but I only have limited experience with this API.

**Comment by wwwebbify** [comment]
Just got the following response back from Polygon support.

> This is actually a known issue. Some of the companies may not be present in the DB at the moment while we work to update the Symbols API. The updated endpoint should be available in the next 6ish weeks.
